# Generated by Django 5.2.14 on 2026-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegram_and_order_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_provider', models.CharField(default='eskiz', max_length=32)),
                ('sms_sender_name', models.CharField(blank=True, default='4546', max_length=32)),
                ('sms_eskiz_email', models.CharField(blank=True, max_length=255)),
                ('sms_eskiz_password', models.CharField(blank=True, max_length=255)),
                ('notify_order_status', models.BooleanField(default=True)),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_payment_received', models.BooleanField(default=True)),
                ('payme_enabled', models.BooleanField(default=False)),
                ('payme_merchant_id', models.CharField(blank=True, max_length=64)),
                ('click_enabled', models.BooleanField(default=False)),
                ('click_merchant_id', models.CharField(blank=True, max_length=64)),
                ('uzum_enabled', models.BooleanField(default=False)),
                ('uzum_merchant_id', models.CharField(blank=True, max_length=64)),
                ('onec_enabled', models.BooleanField(default=False)),
                ('onec_base_url', models.CharField(blank=True, max_length=512)),
                ('onec_api_key', models.CharField(blank=True, max_length=255)),
                ('didox_enabled', models.BooleanField(default=False)),
                ('didox_api_url', models.CharField(blank=True, max_length=512)),
                ('eaktiv_enabled', models.BooleanField(default=False)),
                ('eaktiv_api_url', models.CharField(blank=True, max_length=512)),
                ('maps_provider', models.CharField(default='yandex', max_length=16)),
                ('soliq_api_enabled', models.BooleanField(default=False)),
                ('session_idle_minutes', models.PositiveIntegerField(default=30)),
                ('audit_log_retention_days', models.PositiveIntegerField(default=90)),
                ('enforce_strong_password', models.BooleanField(default=True)),
                ('allow_demo_login', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform settings',
            },
        ),
    ]
