# Generated by Django 5.2.14 on 2026-05-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.CharField(blank=True, help_text='Logo yo‘li yoki URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, help_text='Rasm yo‘li yoki URL (/media/... yoki https://)', max_length=500),
        ),
    ]
