# Generated by Django 5.2.14 on 2026-05-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_media_path_charfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Mahsulot rasmi (/media/... yoki URL)', max_length=500),
        ),
    ]
