# Generated by Django 6.0.4 on 2026-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Qabul qilindi'), ('picking', 'Yig‘ilmoqda'), ('packed', 'Yuklab berildi'), ('in_transit', 'Yo‘lda'), ('delivered', 'Yetkazildi'), ('returned', 'Qaytdi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20),
        ),
    ]
