# Generated by Django 6.0.4 on 2026-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('admin_group_id', models.BigIntegerField(default=-1003852134921, help_text='Asosiy admin guruh (buyurtma/tolov bildirishnomalari)')),
                ('notify_new_orders', models.BooleanField(default=True)),
                ('notify_payments', models.BooleanField(default=True)),
                ('notify_expenses', models.BooleanField(default=True)),
                ('notify_order_status', models.BooleanField(default=True)),
                ('bot_username', models.CharField(blank=True, help_text='getMe dan to‘ldiriladi yoki qo‘lda (@sizsiz)', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram sozlamalari',
            },
        ),
    ]
